global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-book-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']